[package]
name = "test-pkg"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio-metrics = { version = "=0.4.5", features = ["rt"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tokio_unstable)'] }
