[package]
publish = false
name = "configuration_conflict"
version = "0.1.0"
edition = "2021"

[dependencies]

[package.metadata.cargo-semver-checks.lints]
must_use_added = "warn"
function_must_use_added = { level = "deny", required-update = "major" }
