name: "Feature request"
description: "Raising expectations"
labels: 'C-enhancement'
body:
  - type: textarea
    attributes:
      label: "Describe your use case"
      description: "Describe the problem you're trying to solve. This is not mandatory and we *do* consider features without a specific use case, but real problems have priority."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Describe the solution you'd like"
      description: "Please explain what the wanted solution should look like."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Alternatives, if applicable"
      description: "A clear and concise description of any alternative solutions or features you've managed to come up with."
  - type: textarea
    attributes:
      label: "Additional Context"
      description: "Add any other context about the feature request here."
