
pub mod union_inherent_method_now_doc_hidden;

pub mod enum_inherent_method_now_doc_hidden;

pub mod struct_inherent_method_now_doc_hidden;

pub mod doc_hidden_struct_inherent_method_now_doc_hidden;

pub mod struct_and_inherent_method_now_doc_hidden;
