pub mod enum_repr_c_removed;
pub mod enum_variant_added;
pub mod enum_variant_missing;
pub mod item_missing;
pub mod non_exhaustive;
pub mod struct_pub_field_missing;
pub mod struct_repr_c_removed;
pub mod struct_repr_transparent_removed;
pub mod unit_struct_changed_kind;
